export const mockUser={
    "login": "MukeshKaswan1",
    "id": 46134586,
    "node_id": "MDQ6VXNlcjQ2MTM0NTg2",
    "avatar_url": "https://avatars.githubusercontent.com/u/46134586?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/MukeshKaswan1",
    "html_url": "https://github.com/MukeshKaswan1",
    "followers_url": "https://api.github.com/users/MukeshKaswan1/followers",
    "following_url": "https://api.github.com/users/MukeshKaswan1/following{/other_user}",
    "gists_url": "https://api.github.com/users/MukeshKaswan1/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/MukeshKaswan1/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/MukeshKaswan1/subscriptions",
    "organizations_url": "https://api.github.com/users/MukeshKaswan1/orgs",
    "repos_url": "https://api.github.com/users/MukeshKaswan1/repos",
    "events_url": "https://api.github.com/users/MukeshKaswan1/events{/privacy}",
    "received_events_url": "https://api.github.com/users/MukeshKaswan1/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Aryan Sethi",
    "company": null,
    "blog": "https://aryan18.netlify.app/",
    "location": null,
    "email": null,
    "hireable": null,
    "bio": null,
    "twitter_username": "sethi_aryan",
    "public_repos": 36,
    "public_gists": 0,
    "followers": 23,
    "following": 25,
    "created_at": "2018-12-25T15:29:26Z",
    "updated_at": "2024-02-07T13:00:12Z"
  }